runtime: java
env: flex

runtime_config:
  jdk: openjdk21

manual_scaling:
  instances: 1

network:
  session_affinity: true

health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60

resources:
  cpu: 1
  memory_gb: 1.7
  disk_size_gb: 10

env_variables:
  GEOPS_API_KEY: "GEOP_API_KEY_PLACEHOLDER"
  BROKER_HOST: "BROKER_HOST_PLACEHOLDER"
  BROKER_USER: "BROKER_USER_PLACEHOLDER"
  BROKER_PASS: "BROKER_PASS_PLACEHOLDER"