runtime: java17
env: flex
resources:
  cpu: 1
  memory_gb: 1.3
  disk_size_gb: 10
manual_scaling:
  instances: 1
env_variables:
  GEOPS_API_KEY: "GEOP_API_KEY_PLACEHOLDER"
  BROKER_HOST: "BROKER_HOST_PLACEHOLDER"
  BROKER_USER: "BROKER_USER_PLACEHOLDER"
  BROKER_PASS: "BROKER_PASS_PLACEHOLDER"