runtime: java17
instance_class: B2
manual_scaling:
  instances: 1
env_variables:
  GEOPS_API_KEY: "GEOP_API_KEY_PLACEHOLDER"
  BROKER_HOST: "BROKER_HOST_PLACEHOLDER"
  BROKER_USER: "BROKER_USER_PLACEHOLDER"
  BROKER_PASS: "BROKER_PASS_PLACEHOLDER"