server.port=8080

# Enabling the H2-Console (local and remote)
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

# Password for the H2-Console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# You can find your h2-console at: http://localhost:8080/h2-console/
# If you changed the server.port, you must also change it in the URL
# The credentials to log in to the h2 Driver are defined above. Be aware that the h2-console is only accessible when the server is running.

# ----- GTFS static loader properties -----
# Set these values before using the GTFS loader.
gtfs.static-url=https://data.opentransportdata.swiss/dataset/3d2c18f9-9ef1-463f-a249-5c67604efd74/resource/44c51fe4-5441-4359-9438-48869ee658f1/download/gtfs_fp2026_20260325.zip
# gtfs.api-token=YOUR_API_TOKEN
gtfs.local-zip-path=/tmp/gtfs-static.zip
# gtfs.reload-cron=0 0 2 * * *
