spring.application.name=sopra-server

server.port=8080

# Enabling the H2-Console (local and remote)
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

# Password for the H2-Console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=guesSBB
spring.datasource.password=deRemoWettDGsamtpunktzahl
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# You can find your h2-console at: http://localhost:8080/h2-console/
# If you changed the server.port, you must also change it in the URL
# The credentials to log in to the h2 Driver are defined above. Be aware that the h2-console is only accessible when the server is running.

# GeoPS
geops.api.key=${GEOPS_API_KEY:}
geops.mock=false

spring.jpa.open-in-view=false

# RabbitMQ
broker.host=${BROKER_HOST:localhost}
broker.user=${BROKER_USER:system}
broker.pass=${BROKER_PASS:manager}

# Cleanup
cleanup.guest.rate=300000
cleanup.guest.cutoff=10
cleanup.lobby.rate=300000
cleanup.lobby.cutoff=10
cleanup.finished.rate=300000
cleanup.finished.cutoff=5